##
#  UAFaker SBSettings Toggle
##

LIBRARY_NAME = Toggle
Toggle_FILES = Toggle.m
Toggle_INSTALL_PATH = /var/mobile/Library/SBSettings/Toggles/UAFaker/

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/library.mk
